Attempt 3 to fix GHA not failing with pytest

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -46,10 +46,7 @@ jobs:
         run: |
           source .venv/bin/activate
           python -m coverage run -m pytest
-          if $? == 4; then
-          do
-            exit 1
-          done
+          if [ $? -ne 0 ]; then exit 1; fi  # Fail if pytest failed
           python -m coverage report -m --fail-under=85
           python -m coverage xml
       - name: Upload coverage to Codecov
